# Generated by Django 6.0.6 on 2026-06-25 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200)),
                ('descrizione', models.TextField()),
                ('data_ora', models.DateTimeField()),
                ('luogo', models.CharField(max_length=200)),
                ('capienza_massima', models.PositiveIntegerField()),
                ('organizzatore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventi_creati', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Iscrizione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_iscrizione', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iscrizioni', to='eventi.evento')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iscrizioni', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('utente', 'evento')},
            },
        ),
    ]
